name: PHP_CodeSniffer

on: [push, pull_request]

jobs:
  phpstan:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - run: composer install --no-progress --prefer-dist
      - run: composer check-cs